# Application name
spring.application.name=dscommerce

# H2 database connection settings
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# H2 web client configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration to display SQL in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
